#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No color

# Show usage
if [ -z "$1" ] || [ -z "$2" ] ; then
  echo -e "Usage: sudo ./recreate-subvol ${YELLOW}sda3 subvol${NC}"
  echo -e "Recreates btrfs ${YELLOW}subvol${NC} on selected partition"
  exit
fi

# Selected partition
PARTITION=$1
DEVICE=/dev/$PARTITION
LABEL=$2

# Recreate btrfs subvolume
BTRFS_ROOT=linux
mkdir $BTRFS_ROOT
mount $DEVICE -o subvolid=5 $BTRFS_ROOT
btrfs subvolume delete -c $BTRFS_ROOT/@$LABEL
btrfs subvolume create $BTRFS_ROOT/@$LABEL
umount $BTRFS_ROOT
rm -d $BTRFS_ROOT
